// EZODUS: FilesFind/FileFind for FSt_VIRT (host VFS). Real fs in MakeBlkDev.

CDirEntry *FilesFind2(U8 *files_find_mask, I64 fuf_flags)
{
	CDrive		*drive = Fs->cur_dv;
	CDirEntry	*res   = NULL;

	DriveCheck(drive);
	if (drive->fs_type == FSt_VIRT)
		res = VirtFilesFind(files_find_mask, fuf_flags);
	else
	{
		PrintErr("File System Not Supported\n");
		res = NULL;
	}
	if (res)
	{
		DirFilesSort(&res, SK_NAME);
		if (fuf_flags & (FUF_FLATTEN_TREE | FUF_JUST_FILES))
			DirFilesFlatten(res, &res, fuf_flags);
		if (fuf_flags & FUF_CLUS_ORDER)
			DirFilesSort(&res, SK_CLUS);
	}
	return res;
}

public CDirEntry *FilesFind(U8 *files_find_mask, I64 fuf_flags=0)
{
	CDirEntry	*res;
	CDirContext	*dirc;

	if (fuf_flags & ~FUG_FILES_FIND)
		throw('FUF');
	if (fuf_flags & FUF_SINGLE)
	{
		res = CAlloc(sizeof(CDirEntry));
		if (!FileFind(files_find_mask, res))
		{
			Free(res);
			return NULL;
		}
	}
	else if (dirc = DirContextNew(files_find_mask, TRUE))
	{
		res = FilesFind2(dirc->mask, fuf_flags);
		DirContextDel(dirc);
	}
	else
		return NULL;
	return res;
}

public Bool FileFind(U8 *filename, CDirEntry *_de=NULL, I64 fuf_flags=0)
{
	U8			*full_name = NULL;
	CDirEntry	 de;
	CDirContext	*dirc;
	Bool		 res = FALSE;

	if (fuf_flags & ~FUG_FILE_FIND)
		throw('FUF');
	if (!filename || *filename && filename[1] == ':' && !Letter2Drive(*filename, FALSE))
		return FALSE;

	if (dirc = DirContextNew(filename))
	{
		if (dirc->drive->fs_type == FSt_VIRT)
			res = VirtFileFind(dirc->drive, Fs->cur_dir, dirc->mask, &de, fuf_flags);
		else
			PrintErr("File System Not Supported\n");
		if (res && _de)
		{
			if (StrCompare(Fs->cur_dir, "/"))
				full_name = MStrPrint("%C:%s/%s", Drive2Letter(Fs->cur_dv), Fs->cur_dir, de.name);
			else
				full_name = MStrPrint("%C:/%s", Drive2Letter(Fs->cur_dv), de.name);
		}
		DirContextDel(dirc);
	}
	if (!res && fuf_flags & FUF_SCAN_PARENTS)
	{
		if (dirc = DirContextNew(filename))
		{
			while (!res && StrCompare(Fs->cur_dir, "/"))
			{
				Cd("..");
				if (dirc->drive->fs_type == FSt_VIRT)
					res = VirtFileFind(dirc->drive, Fs->cur_dir, dirc->mask, &de, fuf_flags);
				else
					PrintErr("File System Not Supported\n");
			}
			if (res && _de)
			{
				if (StrCompare(Fs->cur_dir, "/"))
					full_name = MStrPrint("%C:%s/%s", Drive2Letter(Fs->cur_dv), Fs->cur_dir, de.name);
				else
					full_name = MStrPrint("%C:/%s", Drive2Letter(Fs->cur_dv), de.name);
			}
			DirContextDel(dirc);
		}
	}
	if (_de)
	{
		if (res)
		{
			MemCopy(_de, &de, sizeof(CDirEntry));
			_de->full_name = full_name;
		}
		else
			MemSet(_de, 0, sizeof(CDirEntry));
	}
	return res;
}
