//Place this file in /Home and change
//anything you want.

U0 UserStartUp()
{//Run each time a user is spawned
	DocTermNew;
	Type("::/Doc/Start.DD");
	LBts(&Fs->display_flags, DISPLAYf_SHOW);
	WinToTop;
	WinZBufUpdate;
	Dir("*", FALSE);
}

U0 ServerStartUp()
{//Run each time a server task is spawned.
	DocTermNew;
	LBts(&Fs->display_flags, DISPLAYf_SHOW);
	WinToTop;
	WinZBufUpdate;
}

U0 StartUpTasks()
{
	CTask *user = User;

	if (sys_boot_src.u16[0] != BOOT_SRC_DVD)
		User;

	WinToTop(user);
	WinTileVert;
	"Boot Time:%7.3fs\n", tS;
	try XTalk(user, "Cd; #include \"Once\";\n");
	catch {}
	Silent;
	try ACInit("::/Kernel/Kernel*.HH;::/Compiler/Compiler*.HH;::/System/*;::/Doc/*;::/Home/*");
	catch {}
	Silent(OFF);

	if (sys_boot_src.u16[0] != BOOT_SRC_RAM)
		try PopUp("ExeFile2(\"::/System/ZSplash.ZC\");");
	catch {}

	if (sys_os_version_nice)
		"\n%s\n\n", sys_os_version_nice;
}
